services:
  app:
    container_name: app
    restart: always
    image: app_image
    env_file:
      - .env

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./:/src

    ports:
      - "16000:8006"

    depends_on:  # Make sure that app postgresql starts first by depending on it.
      - app_postgresql

  app_postgresql:
    container_name: app_postgresql
    restart: always
    hostname: app_postgresql
    image: bitnami/postgresql
    env_file:
      - .env
    volumes:
      - app_postgresql_data:/var/lib/postgresql

    ports:
      - "35432:5432"

  app_redis:  # redis config.
    image: redis:6.2-alpine
    restart: always
    hostname: app_redis
    container_name: app_redis

    env_file:
      - .env

    volumes:
      - app_redis_data:/var/lib/redis

    command:
      - 'redis-server'  # start redis server.
      - '--requirepass 123456'  # set redis password.

    ports:
      - "36379:6379"  # Map the host's port 36379 to the container's port 6379.

  app_minio:  # minio config.
    image: minio/minio:latest
#    restart: always
    container_name: app_minio

    env_file:
      - .env

    volumes:
      - app_minio_data:/data

    command: server /data --console-address ":9001"

    ports:
      - "9000:9000"
      - "9001:9001"

volumes:  # data persistence.
  app_postgresql_data:
    driver: "local"

  app_redis_data:
    driver: "local"

  app_minio_data:
    driver: "local"

networks:
  default:
    external: true
    name: app_network  # network name.
